-- MySQL Script generated by MySQL Workbench
-- Fri 15 Feb 2019 03:48:44 AM EST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Genedalfv2
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Genedalfv2
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Genedalfv2` DEFAULT CHARACTER SET utf8 ;
USE `Genedalfv2` ;

-- -----------------------------------------------------
-- Table `Genedalfv2`.`DEG_lncRNA_roster`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Genedalfv2`.`DEG_lncRNA_roster` (
  `roster_id` INT NOT NULL,
  `cell_line` VARCHAR(45) NULL,
  `lncRNA_name` VARCHAR(100) NULL,
  `replicate_id` INT NULL,
  `path_to_DGE` VARCHAR(200) NULL,
  PRIMARY KEY (`roster_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Genedalfv2`.`Expression`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Genedalfv2`.`Expression` (
  `expression_id` INT NOT NULL,
  `ENSG_id` VARCHAR(45) NULL,
  `gene_symbol` VARCHAR(69) NULL,
  `baseMean` DECIMAL(45,25) NULL,
  `log2FoldChange` DECIMAL(45,25) NULL,
  `lfcSE` DECIMAL(45,25) NULL,
  `pvalue` DECIMAL(45,25) NULL,
  `stat` DECIMAL(45,25) NULL,
  `padj` DECIMAL(45,25) NULL,
  `DEG_lncRNA_roster_roster_id` INT NOT NULL,
  PRIMARY KEY (`expression_id`),
  INDEX `fk_Expression_DEG_lncRNA_roster_idx` (`DEG_lncRNA_roster_roster_id` ASC),
  CONSTRAINT `fk_Expression_DEG_lncRNA_roster`
    FOREIGN KEY (`DEG_lncRNA_roster_roster_id`)
    REFERENCES `Genedalfv2`.`DEG_lncRNA_roster` (`roster_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Genedalfv2`.`PreRanking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Genedalfv2`.`PreRanking` (
  `prerank_id` INT NOT NULL,
  `path_to_prerank` VARCHAR(200) NULL,
  `path_to_GO_enrichment` VARCHAR(200) NULL,
  `Expression_expression_id` INT NOT NULL,
  PRIMARY KEY (`prerank_id`),
  INDEX `fk_PreRanking_Expression1_idx` (`Expression_expression_id` ASC),
  CONSTRAINT `fk_PreRanking_Expression1`
    FOREIGN KEY (`Expression_expression_id`)
    REFERENCES `Genedalfv2`.`Expression` (`expression_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Genedalfv2`.`GSEA_reports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Genedalfv2`.`GSEA_reports` (
  `reports_id` INT NOT NULL,
  `Term` VARCHAR(240) NULL,
  `es` DECIMAL(20,18) NULL,
  `nes` DECIMAL(20,18) NULL,
  `pval` DECIMAL(20,18) NULL,
  `fdr` DECIMAL(20,18) NULL,
  `geneset_size` INT NULL,
  `matched_size` INT NULL,
  `path_to_plot` VARCHAR(250) NULL,
  `PreRanking_prerank_id` INT NOT NULL,
  PRIMARY KEY (`reports_id`),
  INDEX `fk_GSEA_reports_PreRanking1_idx` (`PreRanking_prerank_id` ASC),
  CONSTRAINT `fk_GSEA_reports_PreRanking1`
    FOREIGN KEY (`PreRanking_prerank_id`)
    REFERENCES `Genedalfv2`.`PreRanking` (`prerank_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
